Iphone Data Analysis

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('Data/apple_products.csv')

In [6]:
df.head(5)

,Product Name,Product URL,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Ram
0,"APPLE iPhone 8 Plus (Gold, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-g...,Apple,49900,49900,0,3431,356,MOBEXRGV7EHHTGUH,4.6,2 GB
1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,0,3431,356,MOBEXRGVAC6TJT4F,4.6,2 GB
2,"APPLE iPhone 8 Plus (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,0,3431,356,MOBEXRGVGETABXWZ,4.6,2 GB
3,"APPLE iPhone 8 (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-silver...,Apple,77000,77000,0,11202,794,MOBEXRGVMZWUHCBA,4.5,2 GB
4,"APPLE iPhone 8 (Gold, 256 GB)",https://www.flipkart.com/apple-iphone-8-gold-2...,Apple,77000,77000,0,11202,794,MOBEXRGVPK7PFEJZ,4.5,2 GB

In [8]:
df.count()

Product Name           62
Product URL            62
Brand                  62
Sale Price             62
Mrp                    62
Discount Percentage    62
Number Of Ratings      62
Number Of Reviews      62
Upc                    62
Star Rating            62
Ram                    62
dtype: int64

In [15]:
df['Product Name'].unique()

array(['APPLE iPhone 8 Plus (Gold, 64 GB)',
       'APPLE iPhone 8 Plus (Space Grey, 256 GB)',
       'APPLE iPhone 8 Plus (Silver, 256 GB)',
       'APPLE iPhone 8 (Silver, 256 GB)', 'APPLE iPhone 8 (Gold, 256 GB)',
       'APPLE iPhone 8 Plus (Silver, 64 GB)',
       'APPLE iPhone 8 Plus (Space Grey, 64 GB)',
       'APPLE iPhone 8 (Space Grey, 256 GB)',
       'APPLE iPhone XS Max (Silver, 64 GB)',
       'Apple iPhone XR ((PRODUCT)RED, 128 GB) (Includes EarPods, Power Adapter)',
       'Apple iPhone XR (Black, 64 GB) (Includes EarPods, Power Adapter)',
       'Apple iPhone XR (Coral, 128 GB) (Includes EarPods, Power Adapter)',
       'Apple iPhone XR (Black, 128 GB) (Includes EarPods, Power Adapter)',
       'Apple iPhone XR (White, 128 GB) (Includes EarPods, Power Adapter)',
       'APPLE iPhone 11 Pro Max (Gold, 256 GB)',
       'APPLE iPhone 11 Pro Max (Gold, 64 GB)',
       'APPLE iPhone 11 Pro Max (Midnight Green, 256 GB)',
       'APPLE iPhone 11 Pro Max (Space Grey, 64 GB)',
       'APPLE iPhone 11 Pro (Midnight Green, 64 GB)',
       'APPLE iPhone 11 Pro (Space Grey, 512 GB)',
       'APPLE iPhone 11 Pro Max (Midnight Green, 64 GB)',
       'APPLE iPhone 11 Pro (Midnight Green, 512 GB)',
       'APPLE iPhone 11 Pro (Space Grey, 256 GB)',
       'Apple iPhone SE (White, 256 GB) (Includes EarPods, Power Adapter)',
       'APPLE iPhone 12 Pro (Silver, 512 GB)',
       'APPLE iPhone 12 Pro Max (Pacific Blue, 256 GB)',
       'APPLE iPhone 12 Mini (White, 128 GB)',
       'APPLE iPhone 12 Pro (Graphite, 256 GB)',
       'APPLE iPhone 12 Mini (White, 64 GB)',
       'APPLE iPhone 12 (White, 128 GB)',
       'APPLE iPhone 12 Pro (Graphite, 128 GB)',
       'APPLE iPhone 12 Pro Max (Graphite, 256 GB)',
       'APPLE iPhone 12 Pro Max (Graphite, 128 GB)',
       'APPLE iPhone 12 Mini (Black, 128 GB)',
       'APPLE iPhone 12 Mini (Blue, 128 GB)',
       'APPLE iPhone 12 (Black, 128 GB)',
       'APPLE iPhone 12 (Blue, 128 GB)',
       'APPLE iPhone 12 Pro Max (Silver, 128 GB)',
       'APPLE iPhone 12 Mini (Red, 64 GB)',
       'APPLE iPhone 12 Pro Max (Gold, 128 GB)',
       'APPLE iPhone 12 (Green, 128 GB)',
       'APPLE iPhone 12 Pro (Pacific Blue, 512 GB)',
       'APPLE iPhone 12 (White, 64 GB)', 'APPLE iPhone 12 (Black, 64 GB)',
       'APPLE iPhone 12 (Red, 128 GB)',
       'APPLE iPhone 12 Mini (Black, 64 GB)',
       'APPLE iPhone 12 Pro (Pacific Blue, 128 GB)',
       'APPLE iPhone 12 Pro Max (Pacific Blue, 128 GB)',
       'APPLE iPhone 12 Pro Max (Silver, 256 GB)',
       'APPLE iPhone 12 Pro Max (Gold, 256 GB)',
       'APPLE iPhone 11 (White, 128 GB)', 'APPLE iPhone 11 (Red, 128 GB)',
       'APPLE iPhone SE (White, 64 GB)',
       'APPLE iPhone SE (Black, 128 GB)',
       'APPLE iPhone SE (White, 128 GB)', 'APPLE iPhone SE (Red, 128 GB)',
       'APPLE iPhone 11 (Black, 128 GB)',
       'APPLE iPhone SE (Black, 64 GB)',
       'APPLE iPhone 11 (Purple, 64 GB)',
       'APPLE iPhone 11 (White, 64 GB)', 'APPLE iPhone 11 (Black, 64 GB)',
       'APPLE iPhone 11 (Red, 64 GB)'], dtype=object)

In [16]:
df[df['Mrp']==df['Mrp'].min()]

,Product Name,Product URL,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Ram
52,"APPLE iPhone SE (White, 64 GB)",https://www.flipkart.com/apple-iphone-se-white...,Apple,29999,39900,24,95807,8154,MOBFWQ6BGWDVGF3E,4.5,2 GB
57,"APPLE iPhone SE (Black, 64 GB)",https://www.flipkart.com/apple-iphone-se-black...,Apple,29999,39900,24,95909,8161,MOBFWQ6BR3MK7AUG,4.5,4 GB

In [17]:
df['Mrp']==df['Mrp'].min()

0     False
1     False
2     False
3     False
4     False
      ...
57     True
58    False
59    False
60    False
61    False
Name: Mrp, Length: 62, dtype: bool

In [29]:
df['Model Name'] = df['Product Name'].str[6:15]

In [30]:
df

,Product Name,Product URL,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Ram,Model Name
0,"APPLE iPhone 8 Plus (Gold, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-g...,Apple,49900,49900,0,3431,356,MOBEXRGV7EHHTGUH,4.6,2 GB,iPhone 8
1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,0,3431,356,MOBEXRGVAC6TJT4F,4.6,2 GB,iPhone 8
2,"APPLE iPhone 8 Plus (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,0,3431,356,MOBEXRGVGETABXWZ,4.6,2 GB,iPhone 8
3,"APPLE iPhone 8 (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-silver...,Apple,77000,77000,0,11202,794,MOBEXRGVMZWUHCBA,4.5,2 GB,iPhone 8
4,"APPLE iPhone 8 (Gold, 256 GB)",https://www.flipkart.com/apple-iphone-8-gold-2...,Apple,77000,77000,0,11202,794,MOBEXRGVPK7PFEJZ,4.5,2 GB,iPhone 8
...,...,...,...,...,...,...,...,...,...,...,...,...
57,"APPLE iPhone SE (Black, 64 GB)",https://www.flipkart.com/apple-iphone-se-black...,Apple,29999,39900,24,95909,8161,MOBFWQ6BR3MK7AUG,4.5,4 GB,iPhone SE
58,"APPLE iPhone 11 (Purple, 64 GB)",https://www.flipkart.com/apple-iphone-11-purpl...,Apple,46999,54900,14,43470,3331,MOBFWQ6BTFFJKGKE,4.6,4 GB,iPhone 11
59,"APPLE iPhone 11 (White, 64 GB)",https://www.flipkart.com/apple-iphone-11-white...,Apple,46999,54900,14,43470,3331,MOBFWQ6BVWVEH3XE,4.6,4 GB,iPhone 11
60,"APPLE iPhone 11 (Black, 64 GB)",https://www.flipkart.com/apple-iphone-11-black...,Apple,46999,54900,14,43470,3331,MOBFWQ6BXGJCEYNY,4.6,4 GB,iPhone 11
61,"APPLE iPhone 11 (Red, 64 GB)",https://www.flipkart.com/apple-iphone-11-red-6...,Apple,46999,54900,14,43470,3331,MOBFWQ6BYYV3FCU7,4.6,4 GB,iPhone 11