In [1]:
round(3.5)

4

In [2]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9

In [4]:
["Hello " + str(i) for i in range (10)]

['Hello 0',
 'Hello 1',
 'Hello 2',
 'Hello 3',
 'Hello 4',
 'Hello 5',
 'Hello 6',
 'Hello 7',
 'Hello 8',
 'Hello 9']

In [5]:
[(i,i**2) for i in range(10)]

[(0, 0),
 (1, 1),
 (2, 4),
 (3, 9),
 (4, 16),
 (5, 25),
 (6, 36),
 (7, 49),
 (8, 64),
 (9, 81)]

In [7]:
try:
    a= int(input("enter divisor: "))
    x=1/a
    print(x) 
except:
    print("divided by zero")
else:
    print("no exception")
finally:
    print("block executed")

0.5
no exception
block executed

In [11]:
with open("myfile.txt",'a') as f:
    f.write("\n second file")

In [14]:
with open("myfile.txt",'r') as f:
    for line in f:
        print(line)
f.close()

 first file

 second file

In [15]:
name = 'Rudit'
age ='31'

print(f'my name is {name} and age is {age}')

my name is Rudit and age is 31

In [16]:
lst =[1,2,3,4,5]

lst.append([6,7])

In [17]:
lst

[1, 2, 3, 4, 5, [6, 7]]

In [18]:
lst.extend([8,9])

In [19]:
lst

[1, 2, 3, 4, 5, [6, 7], 8, 9]

In [20]:
lst.insert(1,10)

In [21]:
lst

[1, 10, 2, 3, 4, 5, [6, 7], 8, 9]

In [22]:
d = {'a':1,'b':2,'c':3}

In [25]:
d['d'] = 4

In [26]:
d

{'a': 1, 'b': 2, 'c': 3, 'd': 4}

In [27]:
d['e'] = ['Rudit','Mathews','31']

In [28]:
d

{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': ['Rudit', 'Mathews', '31']}

In [29]:
d['e'][0]

'Rudit'

In [30]:
s = {1,2,3}
s.add(4)

In [31]:
s

{1, 2, 3, 4}

In [35]:
se

set[[1, 10, 2, 3, 4, 5, [6, 7], 8, 9]]

In [41]:
users = [1,2,3,4,5]
for user in users:
    if user%2==0:
        print(f"user {user}")
    else:
        print(f"not user {user}")

not user 1
user 2
not user 3
user 4
not user 5

In [43]:
x=0
while x<5:
    print(x)
    x+=1
    print(x)

0
1
1
2
2
3
3
4
4
5

In [52]:
hello = ['Hello' + "Rudit" for x in range(10) if x%2==0]
print(hello)

['HelloRudit', 'HelloRudit', 'HelloRudit', 'HelloRudit', 'HelloRudit']

In [53]:
import numpy as np
import pandas as pd

In [56]:
print('hello world')

try:
    1 / 0
except ZeroDivisionError:
    print('exception occured')

print('bye world')

hello world
exception occured
bye world

In [57]:
with open("myfile.txt",'r') as f:
    for line in f:
        print(line)
f.close()

 first file

 second file

In [58]:
def myfun():
    print("Hello")
    return None

In [59]:
myfun()

Hello

In [62]:

def double_num(*args):
    for arg in args:
        print(arg*2)
            
    
double_num(1,2,3,4,5)

2
4
6
8
10

In [63]:
def dic(**kwargs):
    for i in kwargs.items():
        print(i)

In [64]:
dic(name = 'Rudit', age =25)

('name', 'Rudit')
('age', 25)

In [67]:
sq_lambda = lambda x:x*x

In [68]:
sq_lambda(2)

4

In [69]:
class Sample():
    pass

In [73]:
x = Sample()
print(type(x))

<class '__main__.Sample'>

In [ ]:
class Dog(object):
    def __init__(self,breed):
        self.breed = breed

In [9]:
class name(object):
    def __init__(self,name,age):
        self.name = name
        self.age = age

In [18]:
s = name(name="Rudit",age=31)
r = name(name="Ruble",age=26)

In [20]:
s.age
r.name

'Ruble'

In [21]:
class Circle(object):
    pi = 3.14
    def __init__(self,radius =1):
        self.radius = radius
    
    def area(self):
        return self.radius*self.radius*Circle.pi
    
    def setRadius(self,radius):
        self.radius = radius
    
    def getRadius(self):
        return self.radius

In [29]:
c = Circle()
c.setRadius(2)
c.area()

12.56

In [6]:
import numpy as np

In [7]:
lst = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]
arr = np.array(lst)

In [8]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [9]:
lst

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]

In [10]:
arr[2][1]

np.int64(12)

In [11]:
arr.shape

(3, 5)

In [12]:
arr.dtype

dtype('int64')

In [13]:
arr.reshape

In [14]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [15]:
import pandas as pd

DataFrames

In [16]:
df = pd.DataFrame(arr)

In [17]:
df

    0   1   2   3   4
0   1   2   3   4   5
1   6   7   8   9  10
2  11  12  13  14  15

In [18]:
df.shape

(3, 5)

In [20]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [23]:
import pandas as pd

# Create data as a dictionary
data = {
    "Name": ["Alice", "Bob", "Charlie", "Diana"],
    "Age": [25, 30, 35, 28],
    "Department": ["HR", "Finance", "IT", "Marketing"],
    "Salary": [50000, 60000, 75000, 55000]
}

# Create DataFrame
df = pd.DataFrame(data,index = ['a','b','c','d'])

df

      Name  Age Department  Salary
a    Alice   25         HR   50000
b      Bob   30    Finance   60000
c  Charlie   35         IT   75000
d    Diana   28  Marketing   55000

In [27]:
df.iloc[0]

Name          Alice
Age              25
Department       HR
Salary        50000
Name: a, dtype: object

Weather Dataset

In [29]:
df = pd.read_csv("A:/Projects/PythonForDE/Data/weather_2012.csv")

In [31]:
df.shape

(8784, 8)

In [33]:
df.tail()

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
8779,2012-12-31 19:00:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,2012-12-31 20:00:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,2012-12-31 21:00:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,2012-12-31 22:00:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,2012-12-31 23:00:00,0.0,-2.1,86,30,11.3,99.89,Snow

In [35]:
df.dtypes

Date/Time              object
Temp (C)              float64
Dew Point Temp (C)    float64
Rel Hum (%)             int64
Wind Spd (km/h)         int64
Visibility (km)       float64
Stn Press (kPa)       float64
Weather                object
dtype: object

In [36]:
df['Date/Time'] = pd.to_datetime(df["Date/Time"])

In [37]:
df.dtypes

Date/Time             datetime64[ns]
Temp (C)                     float64
Dew Point Temp (C)           float64
Rel Hum (%)                    int64
Wind Spd (km/h)                int64
Visibility (km)              float64
Stn Press (kPa)              float64
Weather                       object
dtype: object

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date/Time           8784 non-null   datetime64[ns]
 1   Temp (C)            8784 non-null   float64
 2   Dew Point Temp (C)  8784 non-null   float64
 3   Rel Hum (%)         8784 non-null   int64
 4   Wind Spd (km/h)     8784 non-null   int64
 5   Visibility (km)     8784 non-null   float64
 6   Stn Press (kPa)     8784 non-null   float64
 7   Weather             8784 non-null   object
dtypes: datetime64[ns](1), float64(4), int64(2), object(1)
memory usage: 549.1+ KB

In [41]:
df.index

RangeIndex(start=0, stop=8784, step=1)

In [43]:
df['Weather'].unique()

array(['Fog', 'Freezing Drizzle,Fog', 'Mostly Cloudy', 'Cloudy', 'Rain',
       'Rain Showers', 'Mainly Clear', 'Snow Showers', 'Snow', 'Clear',
       'Freezing Rain,Fog', 'Freezing Rain', 'Freezing Drizzle',
       'Rain,Snow', 'Moderate Snow', 'Freezing Drizzle,Snow',
       'Freezing Rain,Snow Grains', 'Snow,Blowing Snow', 'Freezing Fog',
       'Haze', 'Rain,Fog', 'Drizzle,Fog', 'Drizzle',
       'Freezing Drizzle,Haze', 'Freezing Rain,Haze', 'Snow,Haze',
       'Snow,Fog', 'Snow,Ice Pellets', 'Rain,Haze', 'Thunderstorms,Rain',
       'Thunderstorms,Rain Showers', 'Thunderstorms,Heavy Rain Showers',
       'Thunderstorms,Rain Showers,Fog', 'Thunderstorms',
       'Thunderstorms,Rain,Fog',
       'Thunderstorms,Moderate Rain Showers,Fog', 'Rain Showers,Fog',
       'Rain Showers,Snow Showers', 'Snow Pellets', 'Rain,Snow,Fog',
       'Moderate Rain,Fog', 'Freezing Rain,Ice Pellets,Fog',
       'Drizzle,Ice Pellets,Fog', 'Drizzle,Snow', 'Rain,Ice Pellets',
       'Drizzle,Snow,Fog', 'Rain,Snow Grains', 'Rain,Snow,Ice Pellets',
       'Snow Showers,Fog', 'Moderate Snow,Blowing Snow'], dtype=object)

In [44]:
df['Weather'].nunique()

50

In [45]:
df['Weather'].value_counts()

Weather
Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Thunderstorms,Rain Showers                   16
Haze                                         16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Freezing Drizzle,Fog                          6
Snow,Ice Pellets                              6
Snow,Haze                                     5
Freezing Rain,Fog                             4
Moderate Snow                                 4
Rain,Snow,Ice Pellets                         4
Freezing Fog                                  4
Snow Showers,Fog                              4
Thunderstorms,Rain Showers,Fog                3
Thunderstorms,Rain                            3
Freezing Drizzle,Haze                         3
Rain,Haze                                     3
Drizzle,Snow                                  2
Moderate Snow,Blowing Snow                    2
Thunderstorms                                 2
Freezing Rain,Haze                            2
Rain Showers,Snow Showers                     2
Freezing Rain,Snow Grains                     1
Thunderstorms,Heavy Rain Showers              1
Thunderstorms,Moderate Rain Showers,Fog       1
Thunderstorms,Rain,Fog                        1
Freezing Rain,Ice Pellets,Fog                 1
Moderate Rain,Fog                             1
Rain,Snow,Fog                                 1
Snow Pellets                                  1
Rain Showers,Fog                              1
Drizzle,Ice Pellets,Fog                       1
Rain,Ice Pellets                              1
Rain,Snow Grains                              1
Name: count, dtype: int64

In [48]:
df[:25]

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog
5,2012-01-01 05:00:00,-1.4,-3.3,87,9,6.4,101.27,Fog
6,2012-01-01 06:00:00,-1.5,-3.1,89,7,6.4,101.29,Fog
7,2012-01-01 07:00:00,-1.4,-3.6,85,7,8.0,101.26,Fog
8,2012-01-01 08:00:00,-1.4,-3.6,85,9,8.0,101.23,Fog
9,2012-01-01 09:00:00,-1.3,-3.1,88,15,4.0,101.20,Fog
10,2012-01-01 10:00:00,-1.0,-2.3,91,9,1.2,101.15,Fog
11,2012-01-01 11:00:00,-0.5,-2.1,89,7,4.0,100.98,Fog
12,2012-01-01 12:00:00,-0.2,-2.0,88,9,4.8,100.79,Fog
13,2012-01-01 13:00:00,0.2,-1.7,87,13,4.8,100.58,Fog
14,2012-01-01 14:00:00,0.8,-1.1,87,20,4.8,100.31,Fog
15,2012-01-01 15:00:00,1.8,-0.4,85,22,6.4,100.07,Fog
16,2012-01-01 16:00:00,2.6,-0.2,82,13,12.9,99.93,Mostly Cloudy
17,2012-01-01 17:00:00,3.0,0.0,81,13,16.1,99.81,Cloudy
18,2012-01-01 18:00:00,3.8,1.0,82,15,12.9,99.74,Rain
19,2012-01-01 19:00:00,3.1,1.3,88,15,12.9,99.68,Rain
20,2012-01-01 20:00:00,3.2,1.3,87,19,25.0,99.50,Cloudy
21,2012-01-01 21:00:00,4.0,1.7,85,20,25.0,99.39,Cloudy
22,2012-01-01 22:00:00,4.4,1.9,84,24,19.3,99.32,Rain Showers
23,2012-01-01 23:00:00,5.3,2.0,79,30,25.0,99.31,Cloudy
24,2012-01-02 00:00:00,5.2,1.5,77,35,25.0,99.26,Rain Showers

In [49]:
df[0:25:3]

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
6,2012-01-01 06:00:00,-1.5,-3.1,89,7,6.4,101.29,Fog
9,2012-01-01 09:00:00,-1.3,-3.1,88,15,4.0,101.20,Fog
12,2012-01-01 12:00:00,-0.2,-2.0,88,9,4.8,100.79,Fog
15,2012-01-01 15:00:00,1.8,-0.4,85,22,6.4,100.07,Fog
18,2012-01-01 18:00:00,3.8,1.0,82,15,12.9,99.74,Rain
21,2012-01-01 21:00:00,4.0,1.7,85,20,25.0,99.39,Cloudy
24,2012-01-02 00:00:00,5.2,1.5,77,35,25.0,99.26,Rain Showers

In [51]:
df[0:25:3][['Date/Time','Temp (C)','Weather']]

             Date/Time  Temp (C)               Weather
0  2012-01-01 00:00:00      -1.8                   Fog
3  2012-01-01 03:00:00      -1.5  Freezing Drizzle,Fog
6  2012-01-01 06:00:00      -1.5                   Fog
9  2012-01-01 09:00:00      -1.3                   Fog
12 2012-01-01 12:00:00      -0.2                   Fog
15 2012-01-01 15:00:00       1.8                   Fog
18 2012-01-01 18:00:00       3.8                  Rain
21 2012-01-01 21:00:00       4.0                Cloudy
24 2012-01-02 00:00:00       5.2          Rain Showers

In [55]:
df.loc[0:5,['Temp (C)','Weather']]

   Temp (C)               Weather
0      -1.8                   Fog
1      -1.8                   Fog
2      -1.8  Freezing Drizzle,Fog
3      -1.5  Freezing Drizzle,Fog
4      -1.5                   Fog
5      -1.4                   Fog

In [56]:
df.iloc[0:5,[0,1,7]]

            Date/Time  Temp (C)               Weather
0 2012-01-01 00:00:00      -1.8                   Fog
1 2012-01-01 01:00:00      -1.8                   Fog
2 2012-01-01 02:00:00      -1.8  Freezing Drizzle,Fog
3 2012-01-01 03:00:00      -1.5  Freezing Drizzle,Fog
4 2012-01-01 04:00:00      -1.5                   Fog

In [61]:
df[['Temp (C)','Weather']].iloc[0:5]

   Temp (C)               Weather
0      -1.8                   Fog
1      -1.8                   Fog
2      -1.8  Freezing Drizzle,Fog
3      -1.5  Freezing Drizzle,Fog
4      -1.5                   Fog

In [62]:
df['Weather'].unique()

array(['Fog', 'Freezing Drizzle,Fog', 'Mostly Cloudy', 'Cloudy', 'Rain',
       'Rain Showers', 'Mainly Clear', 'Snow Showers', 'Snow', 'Clear',
       'Freezing Rain,Fog', 'Freezing Rain', 'Freezing Drizzle',
       'Rain,Snow', 'Moderate Snow', 'Freezing Drizzle,Snow',
       'Freezing Rain,Snow Grains', 'Snow,Blowing Snow', 'Freezing Fog',
       'Haze', 'Rain,Fog', 'Drizzle,Fog', 'Drizzle',
       'Freezing Drizzle,Haze', 'Freezing Rain,Haze', 'Snow,Haze',
       'Snow,Fog', 'Snow,Ice Pellets', 'Rain,Haze', 'Thunderstorms,Rain',
       'Thunderstorms,Rain Showers', 'Thunderstorms,Heavy Rain Showers',
       'Thunderstorms,Rain Showers,Fog', 'Thunderstorms',
       'Thunderstorms,Rain,Fog',
       'Thunderstorms,Moderate Rain Showers,Fog', 'Rain Showers,Fog',
       'Rain Showers,Snow Showers', 'Snow Pellets', 'Rain,Snow,Fog',
       'Moderate Rain,Fog', 'Freezing Rain,Ice Pellets,Fog',
       'Drizzle,Ice Pellets,Fog', 'Drizzle,Snow', 'Rain,Ice Pellets',
       'Drizzle,Snow,Fog', 'Rain,Snow Grains', 'Rain,Snow,Ice Pellets',
       'Snow Showers,Fog', 'Moderate Snow,Blowing Snow'], dtype=object)

In [66]:
df_snow = df['Weather'].str.lower().str.contains('snow')

In [72]:
df_snow = df[df_snow]

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
41,2012-01-02 17:00:00,-2.1,-9.5,57,22,25.0,99.66,Snow Showers
44,2012-01-02 20:00:00,-5.6,-13.4,54,24,25.0,100.07,Snow Showers
45,2012-01-02 21:00:00,-5.8,-12.8,58,26,25.0,100.15,Snow Showers
47,2012-01-02 23:00:00,-7.4,-14.1,59,17,19.3,100.27,Snow Showers
48,2012-01-03 00:00:00,-9.0,-16.0,57,28,25.0,100.35,Snow Showers
...,...,...,...,...,...,...,...,...
8779,2012-12-31 19:00:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,2012-12-31 20:00:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,2012-12-31 21:00:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,2012-12-31 22:00:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,2012-12-31 23:00:00,0.0,-2.1,86,30,11.3,99.89,Snow

In [79]:
df_snow = df_snow[(df_snow['Wind Spd (km/h)']>24) & (df_snow['Visibility (km)']==25)]

In [80]:
df_snow

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
45,2012-01-02 21:00:00,-5.8,-12.8,58,26,25.0,100.15,Snow Showers
48,2012-01-03 00:00:00,-9.0,-16.0,57,28,25.0,100.35,Snow Showers
51,2012-01-03 03:00:00,-11.3,-18.7,54,33,25.0,100.61,Snow Showers
217,2012-01-10 01:00:00,2.3,-3.4,66,35,25.0,100.28,Snow
219,2012-01-10 03:00:00,1.6,-2.0,77,28,25.0,100.16,Snow
286,2012-01-12 22:00:00,-4.1,-6.8,81,26,25.0,99.47,Snow
412,2012-01-18 04:00:00,-6.1,-10.9,69,48,25.0,99.36,Snow
451,2012-01-19 19:00:00,-3.6,-12.7,49,30,25.0,100.61,Snow
454,2012-01-19 22:00:00,-4.2,-9.3,68,32,25.0,100.51,Snow
455,2012-01-19 23:00:00,-4.1,-8.9,69,26,25.0,100.47,Snow
461,2012-01-20 05:00:00,-6.3,-12.2,63,33,25.0,100.98,Snow
571,2012-01-24 19:00:00,1.5,-3.2,71,32,25.0,101.01,Snow Showers
575,2012-01-24 23:00:00,1.0,-3.4,72,28,25.0,101.16,Snow Showers
866,2012-02-06 02:00:00,0.1,-4.7,70,32,25.0,100.75,Snow
868,2012-02-06 04:00:00,0.8,-3.7,72,35,25.0,100.68,Snow
1438,2012-02-29 22:00:00,-4.5,-12.3,54,30,25.0,101.14,Snow
1509,2012-03-03 21:00:00,2.9,-3.6,62,46,25.0,98.98,Snow
1510,2012-03-03 22:00:00,2.8,-3.4,64,57,25.0,99.07,Snow
1511,2012-03-03 23:00:00,2.3,-3.1,67,33,25.0,99.18,Snow
2714,2012-04-23 02:00:00,1.1,-1.1,85,44,25.0,100.32,"Rain,Snow"
2715,2012-04-23 03:00:00,1.7,-0.7,84,52,25.0,100.11,"Rain,Snow"
7890,2012-11-24 18:00:00,-0.4,-5.5,68,28,25.0,99.85,Snow Showers
8010,2012-11-29 18:00:00,-4.2,-11.8,55,28,25.0,101.78,Snow Showers
8155,2012-12-05 19:00:00,-1.0,-8.5,57,28,25.0,101.84,Snow
8520,2012-12-21 00:00:00,1.9,-2.1,75,26,25.0,100.60,"Rain,Snow Grains"
8569,2012-12-23 01:00:00,-7.9,-11.8,74,32,25.0,100.27,Snow Showers

In [81]:
def times2(value):
    return value*2

In [85]:
df_snow['Temp (C)'] = df_snow['Temp (C)'].apply(times2)

In [93]:
df_snow

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
45,2012-01-02 21:00:00,-11.6,-12.8,58,26,25.0,100.15,Snow Showers
48,2012-01-03 00:00:00,-18.0,-16.0,57,28,25.0,100.35,Snow Showers
51,2012-01-03 03:00:00,-22.6,-18.7,54,33,25.0,100.61,Snow Showers
217,2012-01-10 01:00:00,4.6,-3.4,66,35,25.0,100.28,Snow
219,2012-01-10 03:00:00,3.2,-2.0,77,28,25.0,100.16,Snow
286,2012-01-12 22:00:00,-8.2,-6.8,81,26,25.0,99.47,Snow
412,2012-01-18 04:00:00,-12.2,-10.9,69,48,25.0,99.36,Snow
451,2012-01-19 19:00:00,-7.2,-12.7,49,30,25.0,100.61,Snow
454,2012-01-19 22:00:00,-8.4,-9.3,68,32,25.0,100.51,Snow
455,2012-01-19 23:00:00,-8.2,-8.9,69,26,25.0,100.47,Snow
461,2012-01-20 05:00:00,-12.6,-12.2,63,33,25.0,100.98,Snow
571,2012-01-24 19:00:00,3.0,-3.2,71,32,25.0,101.01,Snow Showers
575,2012-01-24 23:00:00,2.0,-3.4,72,28,25.0,101.16,Snow Showers
866,2012-02-06 02:00:00,0.2,-4.7,70,32,25.0,100.75,Snow
868,2012-02-06 04:00:00,1.6,-3.7,72,35,25.0,100.68,Snow
1438,2012-02-29 22:00:00,-9.0,-12.3,54,30,25.0,101.14,Snow
1509,2012-03-03 21:00:00,5.8,-3.6,62,46,25.0,98.98,Snow
1510,2012-03-03 22:00:00,5.6,-3.4,64,57,25.0,99.07,Snow
1511,2012-03-03 23:00:00,4.6,-3.1,67,33,25.0,99.18,Snow
2714,2012-04-23 02:00:00,2.2,-1.1,85,44,25.0,100.32,"Rain,Snow"
2715,2012-04-23 03:00:00,3.4,-0.7,84,52,25.0,100.11,"Rain,Snow"
7890,2012-11-24 18:00:00,-0.8,-5.5,68,28,25.0,99.85,Snow Showers
8010,2012-11-29 18:00:00,-8.4,-11.8,55,28,25.0,101.78,Snow Showers
8155,2012-12-05 19:00:00,-2.0,-8.5,57,28,25.0,101.84,Snow
8520,2012-12-21 00:00:00,3.8,-2.1,75,26,25.0,100.60,"Rain,Snow Grains"
8569,2012-12-23 01:00:00,-15.8,-11.8,74,32,25.0,100.27,Snow Showers

In [87]:
df_snow['Wind Spd (km/h)'].describe()

count    26.000000
mean     33.692308
std       8.521827
min      26.000000
25%      28.000000
50%      32.000000
75%      34.500000
max      57.000000
Name: Wind Spd (km/h), dtype: float64

In [ ]:
df_snow_pivot = df_snow.pivot_table(
    values = 'Wind Spd (km/h)',
    index = 'Date/Time',
    columns = 'Weather',
    aggfunc = np.sum
)

C:\Users\RuditMATHEWS\AppData\Local\Temp\ipykernel_45872\2357180938.py:1: FutureWarning: The provided callable <function sum at 0x000002727F48BD80> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df_snow_pivot = df_snow.pivot_table(

In [90]:
df_snow_pivot.reset_index()

Weather           Date/Time  Rain,Snow  Rain,Snow Grains  Snow  Snow Showers
0       2012-01-02 21:00:00        NaN               NaN   NaN          26.0
1       2012-01-03 00:00:00        NaN               NaN   NaN          28.0
2       2012-01-03 03:00:00        NaN               NaN   NaN          33.0
3       2012-01-10 01:00:00        NaN               NaN  35.0           NaN
4       2012-01-10 03:00:00        NaN               NaN  28.0           NaN
5       2012-01-12 22:00:00        NaN               NaN  26.0           NaN
6       2012-01-18 04:00:00        NaN               NaN  48.0           NaN
7       2012-01-19 19:00:00        NaN               NaN  30.0           NaN
8       2012-01-19 22:00:00        NaN               NaN  32.0           NaN
9       2012-01-19 23:00:00        NaN               NaN  26.0           NaN
10      2012-01-20 05:00:00        NaN               NaN  33.0           NaN
11      2012-01-24 19:00:00        NaN               NaN   NaN          32.0
12      2012-01-24 23:00:00        NaN               NaN   NaN          28.0
13      2012-02-06 02:00:00        NaN               NaN  32.0           NaN
14      2012-02-06 04:00:00        NaN               NaN  35.0           NaN
15      2012-02-29 22:00:00        NaN               NaN  30.0           NaN
16      2012-03-03 21:00:00        NaN               NaN  46.0           NaN
17      2012-03-03 22:00:00        NaN               NaN  57.0           NaN
18      2012-03-03 23:00:00        NaN               NaN  33.0           NaN
19      2012-04-23 02:00:00       44.0               NaN   NaN           NaN
20      2012-04-23 03:00:00       52.0               NaN   NaN           NaN
21      2012-11-24 18:00:00        NaN               NaN   NaN          28.0
22      2012-11-29 18:00:00        NaN               NaN   NaN          28.0
23      2012-12-05 19:00:00        NaN               NaN  28.0           NaN
24      2012-12-21 00:00:00        NaN              26.0   NaN           NaN
25      2012-12-23 01:00:00        NaN               NaN   NaN          32.0

In [94]:
mean_temp_df = df_snow.pivot_table(values='Temp (C)', index = df_snow['Date/Time'].dt.month,aggfunc = np.mean)
mean_temp_df

C:\Users\RuditMATHEWS\AppData\Local\Temp\ipykernel_45872\1784325379.py:1: FutureWarning: The provided callable <function mean at 0x000002727F4B11C0> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  mean_temp_df = df_snow.pivot_table(values='Temp (C)', index = df_snow['Date/Time'].dt.month,aggfunc = np.mean)

           Temp (C)
Date/Time
1         -7.400000
2         -2.400000
3          5.333333
4          2.800000
11        -4.600000
12        -4.666667

In [99]:
df.dtypes

Date/Time             datetime64[ns]
Temp (C)                     float64
Dew Point Temp (C)           float64
Rel Hum (%)                    int64
Wind Spd (km/h)                int64
Visibility (km)              float64
Stn Press (kPa)              float64
Weather                       object
dtype: object

In [102]:
mean_wind_df = df.groupby(df['Date/Time'].dt.month)['Wind Spd (km/h)'].mean()
mean_wind_df

Date/Time
1     18.108871
2     14.837644
3     14.514785
4     17.369444
5     12.846774
6     14.681944
7     11.887097
8     13.931452
9     14.108333
10    15.475806
11    13.973611
12    17.614247
Name: Wind Spd (km/h), dtype: float64

In [103]:
import pandas as pd

df1 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['Alice', 'Bob', 'Charlie']
})

df2 = pd.DataFrame({
    'ID': [4, 5, 6],
    'Name': ['David', 'Eva', 'Frank']
})

In [104]:
df1

   ID     Name
0   1    Alice
1   2      Bob
2   3  Charlie

In [105]:
df2

   ID   Name
0   4  David
1   5    Eva
2   6  Frank

In [107]:
df_concat = pd.concat([df1,df2])
df_concat

   ID     Name
0   1    Alice
1   2      Bob
2   3  Charlie
0   4    David
1   5      Eva
2   6    Frank

In [108]:
orders = pd.DataFrame({
    'OrderID': [101, 102, 103, 104],
    'CustomerID': [1, 2, 3, 2],
    'Amount': [250, 450, 300, 150]
})

customers = pd.DataFrame({
    'CustomerID': [1, 2, 3, 4],
    'CustomerName': ['Alice', 'Bob', 'Charlie', 'Diana']
})

In [110]:
df_merge = orders.merge(customers,on ='CustomerID', how = 'left')
df_merge

   OrderID  CustomerID  Amount CustomerName
0      101           1     250        Alice
1      102           2     450          Bob
2      103           3     300      Charlie
3      104           2     150          Bob

In [111]:
df_left = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2']
}, index=['K0', 'K1', 'K2'])

df_right = pd.DataFrame({
    'C': ['C0', 'C1', 'C2'],
    'D': ['D0', 'D1', 'D2']
}, index=['K0', 'K2', 'K3'])

In [116]:
df_join = df_left.join(df_right, how = 'inner')
df_join

     A   B   C   D
K0  A0  B0  C0  D0
K2  A2  B2  C1  D1