In [23]:
import pandas as pd

# Create the DataFrame
data = {
    "project_id": [101, 101, 101, 102, 102, 103, 103],
    "member_id":  ["A",  "A",  "B",  "C",  "C",  "D",  "E"],
    "score":      [80,   90,   90,   75,   85,   95,   100]
}

df = pd.DataFrame(data)

print(df)

   project_id member_id  score
0         101         A     80
1         101         A     90
2         101         B     90
3         102         C     75
4         102         C     85
5         103         D     95
6         103         E    100

In [24]:
df

   project_id member_id  score
0         101         A     80
1         101         A     90
2         101         B     90
3         102         C     75
4         102         C     85
5         103         D     95
6         103         E    100

In [25]:
df1 = df.drop_duplicates(subset=["project_id","member_id"])
df1

   project_id member_id  score
0         101         A     80
2         101         B     90
3         102         C     75
5         103         D     95
6         103         E    100

In [26]:
member_counts = df1.groupby("project_id")["member_id"].nunique()
member_counts

project_id
101    2
102    1
103    2
Name: member_id, dtype: int64

In [27]:
valid = member_counts[member_counts>1].index
valid

Index([101, 103], dtype='int64', name='project_id')

In [28]:
df1

   project_id member_id  score
0         101         A     80
2         101         B     90
3         102         C     75
5         103         D     95
6         103         E    100

In [29]:
df1 = df1[df1["project_id"].isin(valid)]
df1

   project_id member_id  score
0         101         A     80
2         101         B     90
5         103         D     95
6         103         E    100

In [30]:

df1 = df1.groupby("project_id")["score"].mean().reset_index(name = "avg_score")
df1

   project_id  avg_score
0         101       85.0
1         103       97.5